spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=0
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=0
    consul:
      host: 192.168.0.211
      port: 8500
  config:
    import: optional:consul:192.168.0.211:8500

server:
  port: 8085

management:
  security:
    enabled: false
