spring:
  application:
    name: order-service
  cloud:
    consul:
      host: 192.168.0.211
      port: 8500
  config:
    import: optional:consul:192.168.0.211:8500

server:
  port: 8084
---
spring:
  cloud:
    consul:
      discovery:
        instanceZone: zone1
  config:
    activate:
      on-profile: zone1
---
spring:
  cloud:
    consul:
      discovery:
        instanceZone: zone2
  config:
    activate:
      on-profile: zone2
